export const CITIES = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "San Francisco",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Nashville",
  "Detroit",
  "Oklahoma City",
  "Portland",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Omaha",
  "Colorado Springs",
  "Raleigh",
  "Miami",
  "Long Beach",
  "Virginia Beach",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Tampa",
  "New Orleans",
  "Arlington",
  "Cleveland",
  "Bakersfield",
  "Wichita",
  "Aurora",
  "Honolulu",
  "Anaheim",
  "Santa Ana",
  "Cincinnati",
  "Orlando",
  "Pittsburgh",
  "St. Louis",
  "Buffalo",
  "Riverside",
  "Reno",
  "Boise",
  "Salt Lake City",
  "Richmond",
  "Providence",
  "Hartford",
  "San Juan",
  "Newark",
  "Saint Paul",
  "Greensboro",
  "Durham",
  "Lincoln",
  "Irvine",
  "Stockton",
  "Corpus Christi",
  "Anchorage",
  "Henderson",
  "Plano",
  "Jersey City",
  "North Las Vegas",
  "Madison",
  "Chandler",
  "Gilbert",
  "Chula Vista",
  "Fort Wayne",
  "Lubbock",
  "Toledo",
  "St. Petersburg",
  "Laredo",
  "Irving",
  "Chesapeake",
  "Glendale",
  "Winston-Salem",
  "Port St. Lucie",
  "Scottsdale",
  "Garland",
  "Norfolk",
  "Spokane",
  "Fremont",
  "Huntsville"
] as const;
